-record(buffer,{id::integer(),
                user_id::integer(),
                message::string(),
                schedule::string(),
                destination::list(),
                status::string(),
                created::string(),
                modified::string()
               }).
