-record(buffer,{id::integer(),
                user_id::integer(),
                message::string(),
                day::string(),
                time::string(),
                destination=[],
                status::string(),
                created::string(),
                modified::string()
               }).
